# Run as root
sudo: required

# No specific environment necessary
language: generic

# Install Docker support
services:
  - docker

# Install dependencies
install:
  - sudo apt-get install -y curl httpie jq

# Prepare the environment
before_script:
  - .travis/setup.sh

# Build and test the image
script:
  - .travis/build.sh
  - .travis/test.sh

# Create and push a new tag
after_success:
  - .travis/deploy.sh

# Don't build tags to avoid recursion
branches:
  except:
    - /^v[0-9]/
