# http://installer.71m.us/install?url=https://github.com/didstopia/docker-realm-object-server
name: RealmObjectServer
image: ubuntu-14-04-x64
min_size: 1gb
config:
  
  users:
    - name: realm
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']

  apt_sources:
    - source: deb https://apt.dockerproject.org/repo ubuntu-trusty main
      keyid: 2C52609D
      filename: docker.list
  
  apt_update: true
  apt_upgrade: true
  apt_reboot_if_required: true
  
  packages:
    - docker-engine
    - ufw

  runcmd:
    # Setup firewall rules
    - sudo ufw allow outgoing
    - sudo ufw deny incoming
    - sudo ufw allow ssh
    - sudo ufw allow http
    - sudo ufw allow https
    - yes | sudo ufw enable

    # Install Digital Ocean monitoring agent
    - curl -sSL https://agent.digitalocean.com/install.sh | sudo sh

    # Prepare and start Realm Object Server
    - sudo mkdir -p /srv && chown -R realm /srv
    - sudo -u realm docker run -p 80:9080 -p 443:9443 -v /srv/realm/data:/var/lib/realm/object-server -v /srv/realm/config:/etc/realm --restart=unless-stopped --name realm-object-server -d didstopia/realm-object-server:1.4.1-305
