#!/bin/bash

# Catch errors
set -e

# Fix the working directory
cd "${0%/*}"/../

# Get the latest version
REALM_VERSION=`./scripts/version.sh`

# Validate the version using regex
REGEX='^[0-9]+\.[0-9]+'
if [[ ! $REALM_VERSION =~ $REGEX ]]; then
	echo "Version validation failed for $REALM_VERSION. Did semver change or is the API down?"
	exit 1
fi

echo "Docker tag: $DOCKER_TAG"
echo "Realm version: $REALM_VERSION"
echo "Source commit: $SOURCE_COMMIT"

docker build --build-arg REALM_VERSION=$REALM_VERSION -t $IMAGE_NAME:$DOCKER_TAG .
